# Generated by Django 3.1.14 on 2023-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pahchan_card', models.CharField(blank=True, max_length=200, null=True)),
                ('Mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Address_of_the_Artisan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=7, null=True),
        ),
    ]
